name: autopublish

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Publish to single file
      run: dotnet publish .\QuietTime\QuietTime.csproj -o Output  

    - name: Zip files
      run: 7z a QuietTime.zip Output\*

    - name: Print current directory
      run: dir

    - name: Print current directory 2
      run: dir Output

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        version: 0.0.2
      with:
        draft: true
        prerelease: false
        release_name: Release ${version}
        tag_name: ${{ github.ref }}
        body_path: docs\CHANGELOG.MD

    - name: Upload attachment
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: QuietTime.zip
        asset_name: myRelease
        asset_content_type: application/zip
