name: autopublish

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Publish project
      run: dotnet publish QuietTime\QuietTime.csproj /p:PublishProfile=QuietTime\Properties\PublishProfiles\SingleFileOutputProfile.pubxml -o Output

    - name: Upload zipped binary
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: Output/

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: app

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false
        release_name: V${{ github.run_number }}
        tag_name: ${{ github.run_number }}

    - name: Upload attachment
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app
        asset_name: Quiet-Time-v${{ github.run_number }}.zip
        asset_content_type: application/zip
